spring:
  datasource:
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 1
      maximum-pool-size: 5
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://google-io-uat-mysqldb:3306/google-io-uat?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: root
    password: 'root'
  jpa:
    hibernate:
      ddl-auto: update

    database-platform: org.hibernate.dialect.MySQL8Dialect

  main:
    allow-bean-definition-overriding: true

server:
  port: 8081
